accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    UserCreateView,
    UserProfileView,
    UserUpdateView,
    CadastroView,
    DonorCreateView,
    MinhasDoacoesView,
    CadastrarListaView,
    MinhasSolicitacoesView
)


urlpatterns = [

    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('cadastro/beneficiario', UserCreateView.as_view(), name='beneficiario'),
    path('cadastro/doador', DonorCreateView.as_view(), name='doador'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('<int:pk>/profile/', UserUpdateView.as_view(), name='profile-update'),
    path('cadastrar-lista/', CadastrarListaView.as_view(), name='cadastrar-lista'),
    path('minhas-doacoes/', MinhasDoacoesView.as_view(), name='minhas-doacoes'),
    path('minhas-solicitacoes/', MinhasSolicitacoesView.as_view(), name='minhas-solicitacoes'),
]

core/urls.py
from django.urls import path
from .views import (
    HomeView,
    DoacoesView,
    SobreView,
    SejaDoadorView,
    PontosColetaView,
    FacaDoacoesView,
    PontosDoacaoView,
    DoadorListaView
)


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('receba-doacoes/', DoacoesView.as_view(), name='receba-doacoes'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('seja-doador/', SejaDoadorView.as_view(), name='seja-doador'),
    path('pontos-coleta/', PontosColetaView.as_view(), name='pontos-coleta'),
    path('accounts/faca-doacoes/', FacaDoacoesView.as_view(), name='faca-doacoes'),
    path('accounts/pontos-doacao/', PontosDoacaoView.as_view(), name='pontos-doacao'),
    path('accounts/doador-lista/', DoadorListaView.as_view(), name='doador-lista'),

]

educadoa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('materiais/', include('materiais.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from django.db import models
from django.utils import timezone
from datetime import date
from stdimage.models import StdImageField
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)
from pontocoleta.models import PontosColeta


def get_file_path(_instace, filename) -> str:
    today = date.today()
    year = today.strftime("%Y")
    month = today.strftime("%m")
    day = today.strftime("%d")
    file_path = f'avatar/{year}/{month}/{day}/'
    ext = filename.split('.')[-1]
    file_name = f'{file_path}{uuid.uuid4()}.{ext}'
    return file_name


class Base(models.Model):
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Criado em')
    updated_at = models.DateTimeField(default=timezone.now, verbose_name='Atualizado em')
    status = models.BooleanField(default=True)

    class Meta:
        abstract = True


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('O E-mail é Obrigatório')
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            username=username,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser=True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff=True')

        return self._create_user(email, username, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField('E-mail', unique=True)
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=50)
    cpf = models.CharField('CPF', max_length=15, blank=True, null=True)
    fone = models.CharField('Telefone', max_length=15)
    adress = models.CharField(max_length=100, verbose_name='Endereço')
    adress_number = models.CharField(max_length=6, verbose_name='Numero')
    city = models.CharField('Cidade', max_length=30)
    uf = models.CharField(
        max_length=2,
        verbose_name='Estado',
        default='SP',
        choices=(
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )
    is_staff = models.BooleanField('Membro da Equipe', default=False)
    is_donor = models.BooleanField('Doador', default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return f'{self.email}'

    objects = UserManager()

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    imagem = StdImageField(upload_to=get_file_path, blank=True, verbose_name='Imagem',
                           variations={'thumb': {'width': 150, 'height': 150, 'crop': True}}, delete_orphans=True)

    def __str__(self):
        return f'{self.user.email} Profile.'

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'


class Dependente(Base):
    dependente_nome = models.CharField(max_length=50, verbose_name='Nome Completo')
    dependente_nascimento = models.DateField(max_length=10, verbose_name='Data de Nascimento')
    dependente_serie = models.CharField(max_length=10, verbose_name='Ciclo/Série')
    dependente_escola = models.CharField(max_length=50, verbose_name='Escola')
    responsavel = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, blank=False, null=False)
    ponto_coleta = models.ForeignKey(PontosColeta, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return self.dependente_nome

    class Meta:
        verbose_name = 'Dependente'
        verbose_name_plural = 'Dependentes'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import CustomUser, Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        is_donor = self.cleaned_data.get('is_donor')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')

        if not is_donor:
            raise forms.ValidationError('Usuario não é Doador')

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'cpf',
            'fone',
            'adress',
            'adress_number',
            'city',
            'uf',
            'email',
        ]
        labels = {'username': 'Usuário'}

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['email']
        user.is_donor = False

        if commit:
            user.save()
        return user


class DonorUserForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'cpf',
            'fone',
            'adress',
            'adress_number',
            'city',
            'uf',
            'email',
        ]
        labels = {'username': 'Usuário'}

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['email']
        user.is_donor = True

        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = [
            'email',
            'first_name',
            'last_name',
            'cpf',
            'fone',
            'adress',
            'adress_number',
            'city',
            'uf'
        ]


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['imagem']

accounts/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
)
from .forms import (
    UserForm,
    CustomUserChangeForm,
    ProfileChangeForm,
    DonorUserForm
)
from .models import CustomUser, Dependente

# Create your views here.


class CadastroView(TemplateView):
    template_name = 'accounts/index.html'


class UserCreateView(CreateView):
    model = CustomUser
    form_class = UserForm
    template_name = 'accounts/beneficiario.html'
    success_url = reverse_lazy('beneficiario')

    def form_valid(self, form):
        messages.success(self.request, f'Conta Criada com Sucesso!!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Não foi possivel Criar a Conta')
        return super(UserCreateView, self).form_invalid(form)


class DonorCreateView(CreateView):
    model = CustomUser
    form_class = DonorUserForm
    template_name = 'accounts/beneficiario.html'
    success_url = reverse_lazy('donatario')

    def form_valid(self, form):
        messages.success(self.request, f'Conta Criada com Sucesso!!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Não foi possivel Criar a Conta')
        return super(DonorCreateView, self).form_invalid(form)


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    second_form_class = ProfileChangeForm
    template_name = 'accounts/_profile.html'
    success_url = reverse_lazy('profile')

    def post(self, request, *args, **kwargs):
        form = CustomUserChangeForm(request.POST, instance=request.user)
        form2 = ProfileChangeForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            messages.success(request, f'Perfil Atualizado com Sucesso!')
            return redirect('profile')
        else:
            form = CustomUserChangeForm(instance=request.user)
            form2 = ProfileChangeForm(instance=request.user.profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=self.request.user.profile)
        return context

    def form_valid(self, form, *args, **kwargs):
        messages.success(self.request, f'Perfil Atualizado com Sucesso!!')
        return super(UserUpdateView, self).form_valid(form, *args, **kwargs)

    def test_func(self):
        customuser = self.get_object()
        if self.request.user.pk == customuser.pk:
            return True

        return False


class DependenteCreateView(CreateView):
    model = CustomUser
    form_class = UserForm
    template_name = 'accounts/beneficiario.html'
    success_url = reverse_lazy('donatario')

    def form_valid(self, form):
        messages.success(self.request, f'Conta Criada com Sucesso!!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Não foi possivel Criar a Conta')
        return super(DependenteCreateView, self).form_invalid(form)


class MinhasDoacoesView(TemplateView):
    template_name = 'accounts/doadordoacoes.html'


class MinhasSolicitacoesView(TemplateView):
    template_name = 'accounts/solicitacao.html'


class CadastrarListaView(TemplateView):
    template_name = 'accounts/cadastrarlista.html'

accounts/templates/accounts/_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="section-register">
    <div class="container">
        <div class="row">
            <div class="col-5 mx-auto">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Informações Pessoais.</legend>

                        {{ form.media }}
                        {{ form | crispy }}
                        {{ form2 | crispy }}

                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Salvar</button>
                        <a class="btn btn btn-danger btn-lg btn-block" href="{% url 'profile' %}">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/beneficiario.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_anonymous %}
<section id="section-register">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 mr-auto">
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom">Cadastre-se</legend>
                        <div class="row">
                        {{ form.media }}
                        {{ form|crispy}}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <div class="d-flex justify-content-center">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Registrar</button>
                        </div>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="texte-muted">
                        Ja tem uma Conta?<a class="ml-2" href="#">Entrar</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
<meta http-equiv="refresh" content="0; URL='{% url 'profile' %}'"/>
{% endif %}

<script>
   $(document).ready(function(){
   $('#id_fone').phoneBrazil();
   $('.class-phone').phoneBrazil();
   $('input[name=phone]').phoneBrazil();
});
</script>
{% endblock %}

accounts/templates/accounts/cadastrarlista.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h3 class="meuperfil">Meu Perfil :)</h3>
</div>
<div class="boasvindas">
    <h3 id="tituloDoacao">Cadastre a Lista de Materiais</h3>
</div>
    <div class="retangulo2">
        <form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputNome">Nome do aluno:</label>
                    <input type="Nome" class="form-control" id="input">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputPontos">Pontos de Coleta</label>
                    <select id="inputPontos" class="form-control">
                        <option selected> </option>
                        <option value="Ponto1">Ponto1</option>
                        <option value="Ponto1">Ponto2</option>
                        <option value="Ponto3">Ponto3</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputSerie">Ciclo/Série:</label>
                    <input class="form-control" id="Serie">
                </div>
                <div class="form-group col-md-8">
                    <label for="inputEscola">Escola:</label>
                    <input class="form-control" id="Escola">
                </div>
            </div>
        </form>
        <div id="centralizar">
            <table>
                <thead>
                    <tr>
                        <th colspan="4" id="tituloLista">Cadastrar item</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <button id="buttonAdd" type="button" onclick="diminuir1()">-</button>
                            <a>
                                <span id="carrinhoIndex1">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar1()">+</button>
                        </td>
                        <td>Lápis</td>
                    </tr>
                    <tr>
                        <td>
                            <button id="buttonAdd" type="button" onclick="diminuir2()">-</button>
                            <a>
                                <span id="carrinhoIndex2">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar2()">+</button>
                        </td>
                        <td>Caderno</td>
                    </tr>
                    <tr>
                        <td>
                            <button id="buttonAdd" type="button" onclick="diminuir3()">-</button>
                            <a>
                                <span id="carrinhoIndex3">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar3()">+</button>

                        </td>
                        <td>Canetas</td>
                    </tr>

                    <tr>
                        <td>
                            <button id="buttonAdd" type="button" onclick="diminuir4()">-</button>

                            <a>
                                <span id="carrinhoIndex4">0</span>
                            </a>

                            <button id="buttonAdd" type="button" onclick="acrescentar4()">+</button>
                        </td>
                        <td>Borracha</td>
                    </tr>
                    <tr>
                        <td>

                            <button id="buttonAdd" type="button" onclick="diminuir5()">-</button>

                            <a>
                                <span id="carrinhoIndex5">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar5()">+</button>
                        </td>
                        <td>Lápis de cor</td>
                    </tr>
                    <tr>
                        <td>

                            <button id="buttonAdd" type="button" onclick="diminuir6()">-</button>

                            <a>
                                <span id="carrinhoIndex6">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar6()">+</button>
                        </td>
                        <td>Tesoura</td>
                    </tr>
                    <tr>
                        <td>

                            <button id="buttonAdd" type="button" onclick="diminuir7()">-</button>

                            <a>
                                <span id="carrinhoIndex7">0</span>
                            </a>
                            <button id="buttonAdd" type="button" onclick="acrescentar7()">+</button>
                        </td>
                        <td>Mochila</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--Modal-->
    <div class="w3-container">

        <button onclick="document.getElementById('id01').style.display='block'" id="buttonForm3">Finalizar
            cadastro</button>

        <div id="id01" class="w3-modal">
            <div class="w3-modal-content">
                <div class="w3-container">


                    <i class="far fa-check-circle" id="iconModal"></i>

                    <h2>Lista Cadastrada <i class="fas fa-heart" id="heart"></i></h2>

                    <div id="modalText">
                        <h5>Você será notificado por e-mail sobre a</h5>
                        <h5>data da coleta no local selecionado</h5>
                    </div>

                    <div id="buttonSair"
                        style="display: flex;flex-direction: column;justify-content: center;align-items: center;">
                        <a href="{% url 'profile' %}"><button id="buttonModal">Voltar para o painel</button></a>

                        <span onclick="document.getElementById('id01').style.display='none'"
                            class="w3-button w3-display-bottomcenter">ou Sair</span>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!--fim Modal-->
<script>
$(document).ready(function () {
carrinhoIndex1.innerHTML = 0
})

var count1 = 0;

function acrescentar1() {
count1++;
carrinhoIndex1.innerHTML = count1
}
function diminuir1() {
count1--;
carrinhoIndex1.innerHTML = count1

}

$(document).ready(function () {
carrinhoIndex2.innerHTML = 0
})

var count2 = 0;

function acrescentar2() {
count2++;
carrinhoIndex2.innerHTML = count2
}
function diminuir2() {
count2--;
carrinhoIndex2.innerHTML = count2

}

$(document).ready(function () {
carrinhoIndex3.innerHTML = 0
})

var count3 = 0;

function acrescentar3() {
count3++;
carrinhoIndex3.innerHTML = count3
}
function diminuir3() {
count3--;
carrinhoIndex3.innerHTML = count3

}

$(document).ready(function () {
carrinhoIndex4.innerHTML = 0
})

var count4 = 0;

function acrescentar4() {
count4++;
carrinhoIndex4.innerHTML = count4
}
function diminuir4() {
count4--;
carrinhoIndex4.innerHTML = count4

}

$(document).ready(function () {
carrinhoIndex5.innerHTML = 0
})

var count5 = 0;

function acrescentar5() {
count5++;
carrinhoIndex5.innerHTML = count5
}
function diminuir5() {
count5--;
carrinhoIndex5.innerHTML = count5

}

$(document).ready(function () {
carrinhoIndex6.innerHTML = 0
})

var count6 = 0;

function acrescentar6() {
count6++;
carrinhoIndex6.innerHTML = count6
}
function diminuir6() {
count6--;
carrinhoIndex6.innerHTML = count6

}

$(document).ready(function () {
carrinhoIndex7.innerHTML = 0
})

var count7 = 0;

function acrescentar7() {
count7++;
carrinhoIndex7.innerHTML = count7
}
function diminuir7() {
count7--;
carrinhoIndex7.innerHTML = count7
}
</script>
{% endblock %}

accounts/templates/accounts/doadordoacoes.html
{% extends 'base.html' %}
{% block content %}

    <div>
        <h3 class="meuperfil">Meu Perfil :)</h3>
    </div>
    <div class="pedidos">
        <h3>Minhas doações
            <i class="fa fa-hand-holding-heart"
               style="font-size:20px; color:#7173AB;margin-left: 10px;margin-top: 18px;"></i>
        </h3>


    <div class="retangulo1">
        <div class="faixa1">
            <div class="col-sm-12">
                <div class="usuario1 p-2">
                    <h2>#Primeira Doação</h2>
                    <h3>Usuário 1</h3>
                    <h3>Status:</h3>
                    <h3><i class="fas fa-map-marker-alt">
                    </i> Ponto de Coleta:
                    </h3>
                    <h3>Coleta feita por:</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="retangulo1">
        <div class="faixa2">
            <div class="col-sm-12">
                <div class="usuario1 p-2">
                    <h2>#Segunda Doação</h2>
                    <h3>Usuário 2</h3>
                    <h3>Status:</h3>
                    <h3>
                        <i class="fas fa-map-marker-alt"></i> Ponto de Coleta:
                    </h3>
                    <h3>Coleta feita por:</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="retangulo1">
        <div class="faixa2">
            <div class="col-sm-12">
                <div class="usuario1 p-2">
                    <h2>#Terceira Doação</h2>
                    <h3>Usuário 3</h3>
                    <h3>Status:</h3>
                    <h3>
                        <i class="fas fa-map-marker-alt"></i> Ponto de Coleta:
                    </h3>
                    <h3>Coleta feita por:</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="btn-vermais">
        <button type="submit" class="btn-alterar" >Ver mais</button>
    </div>

    <div class="voltar-perfil">
        <a href="{% url 'profile' %}">Voltar ao perfil</a>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="section-cadastro">
    <h1>Em construção</h1>
</section>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sair{% endblock %}

{% block content %}

<section id="section-logout">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 mr-auto">
                <h1>DESCONECTADO</h1>
            </div>
        </div>
        <div class="border-top pt-3">
        <div class="row">
             <div class="col-lg-8 mr-auto">
                    <small class="texte-muted">
                        Você foi desconectado, deseja entrar novamente?<a class="ml-2" href="{% url 'login' %}">Entrar</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="section-profile">
    <div>
        <h3 class="meuperfil">Meu Perfil :)</h3>
    </div>
    <div class="boasvindas">
        <h3 id="titulo">Olá, {{ user.first_name }}, aqui é seu perfil, fique a vontade!</h3>
    </div>
    <div class="retangulo">
    <div class="p-3" id="perfilUser">
        <img class="avatar-img" src="{{ user.profile.imagem.thumb.url }}" alt="Avatar" width="110" height="110">
    </div>
        <a href="#"><p id="legenda">Adicionar imagem</p></a>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
               <div id="icons">
                        <h3 class="subtitulo">Dados Cadastrais</h3>
                        <i class="far fa-user" id="icons"></i>
               </div>
                <ul>
                <li>
                    <a id="lista" href="#">Alterar endereço de e-mail</a>
                </li>
                <li>
                    <a id="lista" href="#">Alterar senha de acesso</a>
                </li>
                <li>
                    <a id="lista" href="#">Alterar seu endereço</a>
                </li>
                <li>
                    <a id="lista" href="#">Alterar dados dos seus dependentes</a>
                </li>
                </ul>
            </div>
            {% if user.is_donor %}
             <div class="col-sm-6">
                    <div id="icons">
                        <a class="subtitulo" href="{% url 'minhas-doacoes' %}">Minhas doações</a>
                        <i class="fa fa-hand-holding-heart" id="icons"></i>
                    </div>
                    <div id="icons">
                        <a class="subtitulo" href="{% url 'faca-doacoes' %}">Ver doações disponíveis</a>
                        <i class="fa fa-box" id="icons"></i>
                    </div>
                </div>
            {% else %}
             <div class="col-sm-6">
                    <div id="icons">
                        <a class="subtitulo" href="{% url 'cadastrar-lista' %}">Cadastrar listas </a>
                        <i class="far fa-file-alt" id="icons"></i>
                    </div>
                    <div id="icons">
                        <a class="subtitulo" href="{% url 'minhas-solicitacoes' %}">Minhas solicitações</a>
                        <i class="fas fa-box-open" id="icons"></i>
                    </div>
               </div>
            {% endif %}
        </div>
    </div>
</div>
</section>
{% endblock %}